AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Metadata:
  PESubscriptions:
    LeadProcessed__e: index.finalizeLead
    NewLead__e: index.handleLead
Resources:
  finalizeLead:
    Properties:
      CodeUri: s3://my-lambda-examples/a9af5c17ef2ef98f5eb60786e2bfcff8
      Description: ''
      FunctionName: finalizeLead
      Handler: index.finalizeLead
      MemorySize: 128
      Role: arn:aws:iam::040552978376:role/service-role/mylambdarole
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
  handleLead:
    Properties:
      CodeUri: s3://my-lambda-examples/a9af5c17ef2ef98f5eb60786e2bfcff8
      Description: ''
      FunctionName: handleLead
      Handler: index.handleLead
      MemorySize: 128
      Role: arn:aws:iam::040552978376:role/service-role/mylambdarole
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
