AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  handleLead:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handleLead
      FunctionName: handleLead
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::040552978376:role/service-role/mylambdarole'
  finalizeLead:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.finalizeLead
      FunctionName: finalizeLead
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::040552978376:role/service-role/mylambdarole'
Metadata:
  PESubscriptions:
    NewLead__e: index.handleLead
    NewContact__e: index.handleContact
